package diagnostics

// One bilingual registry serves both API/page explanations and command output.
var messages = map[string][2]Text{
	"application_pending":             {{"The saved rule differs from the observed runtime rule.", "已保存的规则与观察到的运行规则不同。"}, {"Wait for the application operation and refresh. The observed path does not yet verify the new configuration.", "等待应用操作完成后刷新。已观察到的路径尚不能证明新配置已生效。"}},
	"observation_boundary":            {{"Kernel rules and Go listeners are control-plane observations; business health has not been checked.", "内核规则和 Go 监听属于控制面观察；尚未检查端到端业务健康。"}, {"Refresh after changes. Flowtable counters are best effort; a running flag can also describe unresolved old forwarding.", "变更后刷新诊断。flowtable 计数为尽力统计；running 标志也可能表示尚未排除的旧转发风险。"}},
	"applied":                         {{"The current forwarding path is observed.", "已观察到当前转发路径。"}, {"Verify your actual application separately; a listener or kernel rule does not prove backend availability.", "请另行验证实际业务；监听或内核规则存在不代表后端可用。"}},
	"go_path_reason":                  {{"Go handles at least one path although nftables was requested.", "虽选择 nftables，但至少一条路径由 Go 处理。"}, {"Cross-family, loopback and scoped-address paths use Go; wildcard rules can combine Go and nftables. This is not a firewall bypass.", "跨地址族、回环或带 scope 的地址路径使用 Go；通配监听规则可同时使用 Go 和 nftables。这不是绕过防火墙。"}},
	"runtime_unavailable":             {{"The active forwarding state has not been observed.", "尚未观察到实际转发状态。"}, {"Check service startup logs and refresh. Saved configuration alone does not prove a forwarding path exists.", "检查服务启动日志并刷新。仅保存配置不能证明转发路径已建立。"}},
	"permission_denied":               {{"An operation was rejected for insufficient permission.", "操作因权限不足被拒绝。"}, {"Check the service account, CAP_NET_ADMIN for nftables and CAP_NET_BIND_SERVICE for privileged Go ports. Keep the existing restricted service policy.", "检查服务账户、nftables 所需 CAP_NET_ADMIN 和 Go 低端口所需 CAP_NET_BIND_SERVICE。保留现有受限服务策略。"}},
	"target_resolution_failed":        {{"The target did not resolve to a usable authorized address.", "目标未解析出可用且已授权的地址。"}, {"Check the domain, configured DNS servers and address families. Review the recorded error; this diagnosis does not issue new DNS queries.", "检查域名、配置的 DNS 和地址族。查看记录的错误；诊断本身不会发起新的 DNS 查询。"}},
	"target_policy_denied":            {{"The resolved target is outside the rule's destination authorization.", "解析出的目标不在规则的目标授权范围内。"}, {"Review the intended destination and its explicit CIDR permission. Do not broaden permissions merely to make the rule appear successful.", "核对实际目标及明确的 CIDR 授权。不要仅为显示成功而扩大授权。"}},
	"firewall_compatibility_rejected": {{"Firewall compatibility or its inspection could not be established.", "未能确认防火墙兼容性或完成相关检查。"}, {"Review external hooks and the recorded error with the firewall owner. PortBridge leaves other applications' firewall rules intact and does not force admission.", "与防火墙维护者核对外部 hook 和记录的错误。PortBridge 保留其他应用的规则，不强行放行。"}},
	"listener_failed":                 {{"A Go listener could not start.", "Go 监听启动失败。"}, {"Check whether the port is occupied, the local address exists and binding is permitted. No diagnostic test binds a port.", "检查端口占用、本地地址是否存在及绑定权限。诊断检查不会绑定端口。"}},
	"cleanup_pending":                 {{"Old forwarding or connections have not been proven fully retired.", "尚未证明旧转发路径或连接已完全清理。"}, {"Keep the warning visible. Restore valid instance ownership/recovery evidence and check conntrack permissions and logs; never delete unattributable connections or force success.", "保留此警告。恢复有效的实例归属/恢复记录，检查 conntrack 权限和日志；不要删除无法归属的连接或强制成功。"}},
	"admission_suspended":             {{"New nftables admission is suspended; established connections may remain.", "新的 nftables 转发已暂停接入；既有连接可能仍存在。"}, {"Review the compatibility/cleanup evidence. Suspension is not completed connection retirement and does not authorize automatic fallback.", "检查兼容性和清理证据。暂停接入不等于连接已清理，也不授权自动回退。"}},
	"kernel_unverified":               {{"The current owned kernel state is not verified.", "当前归属内核状态尚未验证。"}, {"Check permission, instance identity and recovery records. Treat the path as unknown until verified; this report makes no ownership changes.", "检查权限、实例身份和恢复记录。验证完成前视为未知；诊断不会改变归属信息。"}},
	"ownership_unverified":            {{"Instance ownership or recovery evidence could not be verified.", "未能验证实例归属或恢复证据。"}, {"Use the original instance configuration and valid recovery records. Do not copy another instance's identity or bypass the ownership checks.", "使用原实例配置和有效恢复记录。不要复制其他实例身份或绕过归属校验。"}},
	"dependency_missing":              {{"A trusted nftables/conntrack dependency is unavailable.", "可信的 nftables/conntrack 依赖不可用。"}, {"Check the distribution's nftables and conntrack packages and root-owned executable permissions. Diagnosis does not install or execute these tools.", "检查发行版 nftables、conntrack 软件包和 root 所有的可执行文件权限。诊断不会安装或执行这些工具。"}},
	"application_failed":              {{"The configuration is saved, but the forwarding path reported an application error.", "配置已保存，但转发路径报告了应用错误。"}, {"Review the recorded evidence and service logs. An accepted API response does not prove successful forwarding or old-connection cleanup.", "核对记录的证据和服务日志。API 接受配置不证明转发成功或旧连接已清理。"}},
	"configuration_invalid":           {{"The configuration could not be read and validated.", "无法读取或校验配置。"}, {"Check the configuration path, read permissions and syntax. Diagnosis does not create a missing configuration or token.", "检查配置路径、读取权限和语法。诊断不会创建缺失的配置或令牌。"}},
	"management_unavailable":          {{"Authenticated live-service diagnostics are unavailable.", "无法获得已认证的运行中服务诊断。"}, {"Check the service, management listener, TLS trust and token file. Local command permissions do not establish the running service's permissions.", "检查服务、管理监听、TLS 信任及令牌文件。本地诊断命令的权限不代表运行中服务的权限。"}},
	"token_inconsistent":              {{"The administrator token file does not match the configured credential.", "管理员令牌文件与配置凭据不一致。"}, {"Check interrupted rotation or missing files. Follow the documented stopped-service administrator-token recovery procedure; diagnosis never rotates tokens.", "检查轮换中断或文件缺失。按文档执行停服后的管理员令牌恢复流程；诊断不会轮换令牌。"}},
	"snapshot_changed":                {{"Configuration changed while this snapshot was being collected.", "采集此快照时配置发生了变化。"}, {"Refresh before comparing application state with the configuration revision.", "刷新后再对照配置版本与应用状态。"}},
	"environment_unavailable":         {{"Some environment details are not readable in this process context.", "当前进程无法读取部分环境信息。"}, {"Unavailable is not proof of failure. Restricted service namespaces can hide kernel files; use the actual rule observations and service logs.", "不可读不代表失败。受限服务命名空间可能隐藏内核文件；请结合实际规则观察和服务日志判断。"}},
}
