'use strict';
let token=sessionStorage.getItem('portbridge_token')||'';let csrf='';let rules=[];let timer=null;let polling=false;let statusRequest=null;
const $=id=>document.getElementById(id);
async function bootstrap(){showTransportWarning();if(token){try{await establishSession();hideLogin();startTimer()}catch(e){showLogin(e.message)}}else showLogin()}
async function api(path,opts={}){opts.headers={...(opts.headers||{}),'Authorization':'Bearer '+token};if(opts.method&&opts.method!=='GET')opts.headers['X-PortBridge-CSRF']=csrf;if(opts.body)opts.headers['Content-Type']='application/json';const r=await fetch(path,opts);if(r.status===401){token='';sessionStorage.removeItem('portbridge_token');showLogin('令牌无效或已轮换');throw new Error('未授权')}if(r.status===204)return null;let j={};try{j=await r.json()}catch{}if(!r.ok)throw new Error(j.error||`请求失败 (${r.status})`);return j}
async function establishSession(){const b=await api('/api/bootstrap');csrf=b.csrf;await loadAll()}
function showTransportWarning(){const loopback=['localhost','127.0.0.1','::1'].includes(location.hostname);$('insecureWarning').classList.toggle('hidden',location.protocol==='https:'||loopback)}
function stopTimer(){polling=false;clearTimeout(timer);timer=null}
function clearManagementView(){csrf='';rules=[];$('uptime').textContent='运行时间 --';for(const id of ['ruleCount','runningCount','activeTCP','activeUDP'])$(id).textContent='0';$('bytesUp').textContent='0 B';$('bytesDown').textContent='0 B';renderRules([]);for(const id of ['autoACL','whiteACL','bootstrapACL'])renderChips(id,[]);$('settingsForm').reset();$('whitelist').value='';$('dnsServers').value='';$('tlsCertFile').value='';$('tlsKeyFile').value='';$('settingsMsg').textContent='';$('ruleForm').reset();$('ruleId').value='';$('ruleError').textContent='';if($('ruleDialog').open)$('ruleDialog').close();$('tokenResult').textContent='';$('tokenResult').classList.add('hidden');$('toast').textContent='';$('toast').classList.remove('show');renderTLS(null);syncStrictUI()}
function showLogin(msg=''){$('login').classList.remove('hidden');$('loginError').textContent=msg;stopTimer();clearManagementView()}function hideLogin(){$('login').classList.add('hidden');$('loginError').textContent=''}function startTimer(){stopTimer();polling=true;const poll=async()=>{await loadStatus();if(polling)timer=setTimeout(poll,500)};timer=setTimeout(poll,500)}
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();token=$('tokenInput').value.trim();try{await establishSession();sessionStorage.setItem('portbridge_token',token);$('tokenInput').value='';hideLogin();startTimer()}catch(err){showLogin(err.message)}});
$('logoutBtn').onclick=()=>{token='';sessionStorage.removeItem('portbridge_token');showLogin()};
async function loadAll(){await Promise.all([loadConfig(),loadStatus()])}
async function loadConfig(){const requestToken=token;const c=await api('/api/config');if(!token||token!==requestToken)return;rules=c.rules||[];$('autoLan').checked=c.web.auto_lan_acl;$('strictAllowlist').checked=!!c.web.strict_ip_allowlist;$('whitelist').value=(c.web.whitelist||[]).join('\n');$('dnsServers').value=(c.web.dns_servers||[]).join('\n');$('webPort').value=c.web.port;$('webIPv4').value=c.web.listen_ipv4;$('webIPv6').value=c.web.listen_ipv6;$('tlsCertFile').value=c.web.tls_cert_file||'';$('tlsKeyFile').value=c.web.tls_key_file||'';$('tlsMinVersion').value=c.web.tls_min_version==='1.3'?'1.3':'1.2';renderTLS(c.https);syncStrictUI()}
async function loadStatus(){if(statusRequest)return statusRequest;const requestToken=token;statusRequest=(async()=>{try{const s=await api('/api/status');if(!token||token!==requestToken)return;rules=s.rules.map(x=>x.rule);renderStatus(s)}catch(e){if(token===requestToken&&token)console.error(e)}})();try{return await statusRequest}finally{statusRequest=null}}
function renderStatus(s){$('uptime').textContent='运行时间 '+duration(s.uptime_seconds);$('ruleCount').textContent=s.rules.length;$('runningCount').textContent=s.rules.filter(x=>x.stats.running).length;const sum=(k)=>s.rules.reduce((a,x)=>a+(x.stats[k]||0),0);$('activeTCP').textContent=sum('active_tcp');$('activeUDP').textContent=sum('active_udp_sessions');$('bytesUp').textContent=bytes(sum('bytes_up'));$('bytesDown').textContent=bytes(sum('bytes_down'));renderRules(s.rules);renderChips('autoACL',s.acl.auto);renderChips('whiteACL',s.acl.whitelist);renderChips('bootstrapACL',s.acl.bootstrap)}
function protocolText(protocol){return protocol==='both'?'TCP + UDP':protocol.toUpperCase()}
function dataPlaneText(v){return v==='nftables'?'nftables + flowtable':v==='go-proxy'?'Go proxy':v==='hybrid'?'混合（flowtable / Go）':'—'}
function rulePlaneText(v){return v==='go'?'GO':'nftables 优先'}
function activityText(r,st,dp){if(dp==='nftables')return `内核 flowtable 转发<span class="sub">连接由 conntrack 管理</span>`;const suffix=dp==='hybrid'?'<span class="sub">计数仅含 Go 跨族路径</span>':'';const udpStats=`<span class="sub">UDP 包 ${st.udp_packets_up||0} ↑ / ${st.udp_packets_down||0} ↓ / 丢弃 ${st.udp_drops||0}</span>`;if(r.protocol==='both')return `TCP ${st.active_tcp} / UDP ${st.active_udp_sessions}<span class="sub">累计 TCP ${st.total_tcp} / UDP ${st.total_udp_sessions}</span>${udpStats}${suffix}`;return `${r.protocol==='tcp'?st.active_tcp:st.active_udp_sessions}<span class="sub">累计 ${r.protocol==='tcp'?st.total_tcp:st.total_udp_sessions}</span>${r.protocol==='udp'?udpStats:''}${suffix}`}
function renderRules(items){const body=$('rulesBody');body.textContent='';$('emptyRules').style.display=items.length?'none':'block';for(const x of items){const r=x.rule,st=x.stats,dp=x.data_plane||'go-proxy';const tr=document.createElement('tr');const state=st.last_error?['err','错误']:st.running?['on','运行中']:['','已停止'];tr.innerHTML=`<td><span class="status"><i class="dot ${state[0]}"></i>${state[1]}</span>${st.last_error?`<span class="sub" title="${esc(st.last_error)}">${esc(short(st.last_error,34))}</span>`:''}</td><td>${esc(r.name)}</td><td><span class="pill">${esc(protocolText(r.protocol))}</span></td><td><span class="pill">${esc(rulePlaneText(r.data_plane))}</span><span class="sub">实际：${esc(dataPlaneText(dp))}</span></td><td class="nowrap">${esc(endpoint(r.listen_host,r.listen_port,r.listen_port_end))}</td><td class="nowrap">${esc(endpoint(r.target_host,r.target_port,r.target_port_end))}</td><td>${activityText(r,st,dp)}</td><td>${bytes(st.bytes_up)} ↑<span class="sub">${bytes(st.bytes_down)} ↓</span></td><td><div class="actions"><button class="ghost" data-edit="${esc(r.id)}">编辑</button><button class="danger" data-del="${esc(r.id)}">删除</button></div></td>`;body.appendChild(tr)}body.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openRule(b.dataset.edit));body.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>deleteRule(b.dataset.del))}
function renderChips(id,list){const el=$(id);el.textContent='';if(!list||!list.length){el.innerHTML='<span class="muted">无</span>';return}for(const v of list){const c=document.createElement('span');c.className='chip';c.textContent=v;el.appendChild(c)}}
function syncStrictUI(){const strict=$('strictAllowlist').checked;if(strict)$('autoLan').checked=false;$('autoLan').disabled=strict;$('strictAllowlist').disabled=location.protocol!=='https:'&&!strict}
$('strictAllowlist').addEventListener('change',syncStrictUI);
$('settingsForm').addEventListener('submit',async e=>{e.preventDefault();$('settingsMsg').textContent='';try{const j=await api('/api/settings',{method:'PUT',body:JSON.stringify({auto_lan_acl:$('autoLan').checked,strict_ip_allowlist:$('strictAllowlist').checked,allow_insecure_http:false,whitelist:$('whitelist').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean),dns_servers:$('dnsServers').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean),port:Number($('webPort').value),listen_ipv4:$('webIPv4').value.trim(),listen_ipv6:$('webIPv6').value.trim(),tls_cert_file:$('tlsCertFile').value.trim(),tls_key_file:$('tlsKeyFile').value.trim(),tls_min_version:$('tlsMinVersion').value})});$('settingsMsg').textContent=j.restart_required?'已保存。安全模式、TLS、监听地址或端口变更需重启服务；重启前当前进程配置不变。':'已保存并立即生效。';await loadAll()}catch(err){$('settingsMsg').textContent=err.message}});
$('rotateTokenBtn').onclick=async()=>{if(!confirm('轮换后当前令牌立即失效。继续吗？'))return;try{const j=await api('/api/token/rotate',{method:'POST'});$('tokenResult').classList.remove('hidden');$('tokenResult').textContent='新令牌（仅显示一次）：'+j.token;token=j.token;sessionStorage.setItem('portbridge_token',token);toast('管理员令牌已轮换')}catch(e){toast(e.message)}};
$('addRuleBtn').onclick=()=>openRule('');$('closeDialog').onclick=closeRule;$('cancelDialog').onclick=closeRule;
function openRule(id){const r=rules.find(x=>x.id===id);$('dialogTitle').textContent=r?'编辑规则':'新增规则';$('ruleId').value=r?.id||'';$('ruleName').value=r?.name||'';$('protocol').value=r?.protocol||'tcp';$('ruleDataPlane').value=r?.data_plane||'nftables';$('enabled').checked=r?.enabled??true;$('listenHost').value=r?.listen_host||'*';$('listenPort').value=r?.listen_port||'';$('listenPortEnd').value=r?.listen_port_end||'';$('targetHost').value=r?.target_host||'';$('targetPort').value=r?.target_port||'';$('targetPortEnd').value=r?.target_port_end||'';$('allowPrivateTarget').checked=!!r?.allow_private_target;$('targetCIDRAllowlist').value=(r?.target_cidr_allowlist||[]).join('\n');$('connectTimeout').value=r?.connect_timeout_seconds||10;$('tcpIdleTimeout').value=r?.tcp_idle_timeout_seconds||300;$('maxTcpConnections').value=r?.max_tcp_connections||2048;$('maxTcpConnectionsPerSource').value=r?.max_tcp_connections_per_source||256;$('udpTimeout').value=r?.udp_idle_timeout_seconds||60;$('maxUdpSessions').value=r?.max_udp_sessions||4096;$('maxUdpSessionsPerSource').value=r?.max_udp_sessions_per_source||512;$('udpNewSessionsPerSecond').value=r?.udp_new_sessions_per_second_per_source||1000;$('udpPacketsPerSecond').value=r?.udp_packets_per_second_per_source||100000;$('udpWorkers').value=r?.udp_workers??0;$('udpBatchSize').value=r?.udp_batch_size||64;$('udpPacketBufferSize').value=r?.udp_packet_buffer_size||2048;$('udpListenerBufferBytes').value=r?.udp_listener_buffer_bytes||4194304;$('udpSessionBufferBytes').value=r?.udp_session_buffer_bytes||65536;$('ruleError').textContent='';$('ruleDialog').showModal()}
function closeRule(){$('ruleDialog').close()}
$('ruleForm').addEventListener('submit',async e=>{e.preventDefault();const id=$('ruleId').value;const r={name:$('ruleName').value.trim(),protocol:$('protocol').value,data_plane:$('ruleDataPlane').value,listen_host:$('listenHost').value.trim(),listen_port:Number($('listenPort').value),listen_port_end:Number($('listenPortEnd').value)||0,target_host:$('targetHost').value.trim(),target_port:Number($('targetPort').value),target_port_end:Number($('targetPortEnd').value)||0,enabled:$('enabled').checked,allow_private_target:$('allowPrivateTarget').checked,target_cidr_allowlist:$('targetCIDRAllowlist').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean),connect_timeout_seconds:Number($('connectTimeout').value),tcp_idle_timeout_seconds:Number($('tcpIdleTimeout').value),max_tcp_connections:Number($('maxTcpConnections').value),max_tcp_connections_per_source:Number($('maxTcpConnectionsPerSource').value),udp_idle_timeout_seconds:Number($('udpTimeout').value),max_udp_sessions:Number($('maxUdpSessions').value),max_udp_sessions_per_source:Number($('maxUdpSessionsPerSource').value),udp_new_sessions_per_second_per_source:Number($('udpNewSessionsPerSecond').value),udp_packets_per_second_per_source:Number($('udpPacketsPerSecond').value),udp_workers:Number($('udpWorkers').value),udp_batch_size:Number($('udpBatchSize').value),udp_packet_buffer_size:Number($('udpPacketBufferSize').value),udp_listener_buffer_bytes:Number($('udpListenerBufferBytes').value),udp_session_buffer_bytes:Number($('udpSessionBufferBytes').value)};try{await api(id?`/api/rules/${id}`:'/api/rules',{method:id?'PUT':'POST',body:JSON.stringify(r)});closeRule();toast(id?'规则已更新':'规则已创建');await loadAll()}catch(err){$('ruleError').textContent=err.message}});
async function deleteRule(id){const r=rules.find(x=>x.id===id);if(!confirm(`删除规则“${r?.name||id}”？`))return;try{await api(`/api/rules/${id}`,{method:'DELETE'});toast('规则已删除');await loadAll()}catch(e){toast(e.message)}}
function endpoint(host,port,end){const portText=end&&end!==port?`${port}-${end}`:`${port}`;if(host==='*')return `*:${portText}`;return host.includes(':')?`[${host}]:${portText}`:`${host}:${portText}`}
function duration(sec){sec=Math.max(0,Number(sec)||0);const d=Math.floor(sec/86400),h=Math.floor(sec%86400/3600),m=Math.floor(sec%3600/60);return d?`${d}天 ${h}时`:h?`${h}时 ${m}分`:`${m}分`}
function bytes(n){n=Number(n)||0;const u=['B','KiB','MiB','GiB','TiB'];let i=0;while(n>=1024&&i<u.length-1){n/=1024;i++}return `${n.toFixed(i?1:0)} ${u[i]}`}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function short(s,n){s=String(s);return s.length>n?s.slice(0,n)+'…':s}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
syncStrictUI();bootstrap().catch(e=>showLogin(e.message));

function renderTLS(info){const cert=info?.certificate;const warning=$('selfSignedWarning');warning.classList.toggle('hidden',!cert?.enabled||!cert.self_signed);$('certificateStatus').textContent=cert?.enabled?(cert.self_signed?'当前进程使用自签证书。':'当前进程使用非自签证书，信任状态由客户端验证。')+' SHA-256: '+cert.sha256+'；有效期至 '+new Date(cert.not_after).toLocaleString():'尚未加载 HTTPS 证书。';}
